export const UI_STRINGS = {
  app_title: 'GEPA — General English Placement Assessment',
  app_subtitle: 'Free Diagnostic Beta — Indicative placement estimate across core communicative skills',
  start_screen: {
    badge: 'Diagnostic Beta',
    headline: 'Discover Your Communicative Profile',
    subheadline:
      'A low-friction, computer-adaptive diagnostic assessment designed to provide an indicative placement estimate referencing international standards.',
    goal_label: 'Target Destination (Optional)',
    goal_hint: 'Select the goal you are preparing for to receive tailored readiness advice.',
    goals: [
      { id: 'General', label: 'General English' },
      { id: 'OET', label: 'OET (Healthcare)' },
      { id: 'IELTS', label: 'IELTS Preparation' },
      { id: 'TOEFL iBT', label: 'TOEFL iBT' },
      { id: 'PTE Academic', label: 'PTE Academic' },
      { id: 'Cambridge/DET/other', label: 'Cambridge / DET / Other' },
      { id: 'University', label: 'University Entrance' },
      { id: 'Work', label: 'Work & Professional' },
    ],
    language_label: 'Instruction Language',
    consent_privacy: 'I understand this is a free diagnostic assessment and agree to the privacy policy.',
    consent_research: 'Allow my anonymised response telemetry to support ongoing research and test enhancement.',
    start_btn: 'Begin Assessment',
    about_test_btn: 'What is this assessment?',
    questionnaire_title: 'About you (Optional & Skippable)',
    age_label: 'Age bracket',
    l1_label: 'First language (L1)',
    device_label: 'Device environment',
  },
  worked_example: {
    badge: 'Walkthrough',
    title: 'How Question Delivery Works',
    instructions:
      'This unscored example shows how the test interface functions. Read the prompt, select an option using keyboard or mouse, and confirm your selection.',
    explanation:
      'Notice the countdown timer above. Each question has a dedicated server-enforced deadline. When you are ready, confirm your choice to continue.',
    audio_test_title: 'Sound Check',
    audio_test_desc: 'Press play to verify your audio equipment before starting the test.',
    continue_btn: 'Start Diagnostic Assessment',
  },
  navigation: {
    next: 'Next Question',
    submit: 'Confirm Choice',
    submit_testlet: 'Submit Testlet',
    continue: 'Continue',
    pause: 'Pause Assessment',
    resume: 'Resume Assessment',
    skip_module: 'Skip to Next Section',
  },
  timer: {
    warning_60s: '60 seconds remaining',
    warning_15s: '15 seconds remaining',
    timeout_msg: 'Time is up for this question. Proceeding to the next question.',
  },
  results: {
    title: 'Diagnostic Profile & Observed Skills',
    disclaimer: 'GEPA does not predict official exam scores.',
    retest_title: 'Recommended Retest Window',
    delete_data_btn: 'Delete My Data',
    receptive_only_notice:
      'This foundation profile summarizes receptive skills only. Speaking and Writing have not yet been evaluated.',
    claims_title: 'What this result is and is not',
    claims_is_title: 'What this result is',
    claims_is_points: [
      'Indicative placement estimate based on observed performance',
      'Diagnostic communicative profile highlighting strengths and growth areas',
      'Developmental guidance to help prioritize future study',
      'Provisional placement with Moderate or Low confidence',
    ],
    claims_not_title: 'What this result is not',
    claims_not_points: [
      'GEPA does not predict official exam scores.',
      'Not an institutional or high-stakes examination',
      'Does not provide external admissions or licensing equivalence',
      'Does not report fractional or plus/minus sub-levels',
    ],
  },
  accessibility: {
    title: 'Display & Access Settings',
    text_size: 'Text Scaling',
    spacing: 'Line and Letter Spacing',
    spacing_normal: 'Normal',
    spacing_wide: 'Wide Spacing',
    high_contrast: 'High Contrast Mode',
    extended_time: 'Extended Time (1.5×)',
    transcript: 'Transcript Assistance Mode',
  },
};
